package se.sensera.banking.exceptions;

public enum UseExceptionType {
    USER_PERSONAL_ID_NOT_UNIQUE,
    ACCOUNT_NAME_NOT_UNIQUE,
    CANNOT_ADD_OWNER_AS_USER,
    USER_ALREADY_ASSIGNED_TO_THIS_ACCOUNT,
    ACCOUNT_NOT_FOUND,
    NOT_OWNER,
    NOT_ACTIVE,
    USER_NOT_ASSIGNED_TO_THIS_ACCOUNT,
    NOT_ALLOWED,
    NOT_FUNDED,
    NOT_FOUND,
    USER_NOT_FOUND,
    ACCOUNT_NOT_ACTIVE
    ;
}
